
# Promtail Helm chart values (syslog receiver example)
config:
  snippets:
    extraScrapeConfigs: |
      - job_name: syslog
        syslog:
          listen_address: 0.0.0.0:1514
          idle_timeout: 60s
          label_structured_data: true
          labels:
            job: "syslog"
        relabel_configs:
          - source_labels: ['__syslog_message_hostname']
            target_label: host
          - source_labels: ['__syslog_message_severity']
            target_label: severity
          - source_labels: ['__syslog_message_facility']
            target_label: facility
service:
  enabled: true
  ports:
    - name: syslog
      port: 1514
      targetPort: 1514
      protocol: TCP
    - name: syslog-udp
      port: 1514
      targetPort: 1514
      protocol: UDP
