
replicaCount: 2

image:
  repository: ghcr.io/OWNER/REPO   # overwritten by CI
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: false
  className: ""
  hosts:
    - host: demoapp.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 75

podSecurityContext: {}
securityContext:
  runAsNonRoot: true
  runAsUser: 10001

nodeSelector: {}
tolerations: []
affinity: {}
